name = "spark_ml_kem"
version = "1.0.0"
description = "SPARK Ada ML-KEM-1024 (FIPS 203, Kyber) post-quantum key encapsulation"
licenses = "Apache-2.0"
authors = ["AnubisQuantumCipher <sic.tau@pm.me>"]
maintainers = ["AnubisQuantumCipher <sic.tau@pm.me>"]
website = "https://github.com/AnubisQuantumCipher/spark_ml_kem"
tags = ["post-quantum", "kyber", "kem", "spark", "fips-203"]
project-files = ["spark_ml_kem.gpr"]

long-description = """
ML-KEM-1024 post-quantum key encapsulation (FIPS 203). IND-CCA2 security, NTT-based polynomial arithmetic.
"""
